---
- hosts: all
  become: true
  tasks:
  - name: update apt
    apt: update_cache=yes force_apt_get=yes
  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  - name: assicurati che docker sia attivo
    service:
      name: docker
      state: started
      enabled: yes
  #tests123

